server:
  port: 8445
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/
spring:
  application:
    name: gateway-deploy
  cloud:
    config:
      uri: http://${CONFIG_ZONE_HOST:localhost}:${CONFIG_ZONE_PORT:8888}/               #config server 端地址
      profile: dev                                      #项目配置文件选择
      label: master                                     #git仓库的分支
      discovery:
        enabled: true
        service-id: config-server                       #config-server服务名称
  rabbitmq:
    host: ${RABBIT_MQ_HOST:192.168.80.160}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:ecommerce}
    password: ${RABBIT_MQ_PASSWORD:ecommerce}
    virtual-host: ${RABBIT_VIRTUAL-HOST:/ecommerce}