server:
  port: 10010
spring:
  application:
    name: ec-zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5 # 每5秒
zuul:
  prefix: /api
  routes:
    commodity-service: /item/**
    search-service: /search/**
    auth-service: /auth/**
    cart-service: /cart/**
    pay-service: /order/**
    # upload为图片,静态文件上传需要缓存zuul,这样浪费资源
    # 因而一般的配置nginx,将image.ecommerce.com/upload上
    # 由于nginx已经配置upload路径,因而完整的路径是image.ecommerce.com/upload/upload才能被zuul识别并跳转至upload-service
    # 如按照上面配置,则路径会变为image.ecommerce.com/upload/**  因而如下方缩写,且strip-prefix=false
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  # 使得Cookie的Host生效,使得手动修改Cookie不会跨域
  sensitive-headers:
  add-host-header: true
ribbon: # 负载均衡
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: false # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 50000 # 熔断超时时长：50000ms
ec:
  jwt:
    pubKeyPath: classpath:RSA/id_rsa.pub # 公钥地址
    cookieName: EC_TOKEN # cookie的名称
  filter:
    allowPaths:
    - /api/auth
    - /api/search
    - /api/user/register
    - /api/user/check
    - /api/user/code
    - /api/item