server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://192.168.80.138:3306/ecommerce
    username: root
    password: 123456
  redis:
    host: 192.168.80.160
  rabbitmq:
    username: ecommerce
    password: ecommerce
    virtual-host: /ecommerce
    host: 192.168.80.160
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  # instance:
    # prefer-ip-address: true
    # ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.ec.user.pojo