
eureka:
  client:
    fetch-registry: false	# 因为是Server,所以不需要定时获取同步
    register-with-eureka: false # 服务端不需要注册自己
    service-url:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 5000 # 每隔5秒进行一次服务列表清理
server:
  port: ${EUREKA_PORT:8761}
spring:
  application:
    name: ec-registry
  rabbitmq:
    host: ${RABBIT_MQ_HOST:192.168.80.160}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:ecommerce}
    password: ${RABBIT_MQ_PASSWORD:ecommerce}
    virtual-host: ${RABBIT_VIRTUAL-HOST:/ecommerce}
logging:
  level:
    com.netflix: warn
    