server:
  port: ${EUREKA_PORT:8071}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/
spring:
  application:
    name: ec-bus
  rabbitmq:
    host: ${RABBIT_MQ_HOST:192.168.80.160}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:ecommerce}
    password: ${RABBIT_MQ_PASSWORD:ecommerce}
    virtual-host: ${RABBIT_VIRTUAL-HOST:/ecommerce}